name: calo
description: Calo Tiket

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^0.5.1
  cupertino_icons: ^0.1.2
  flutter_swiper: ^1.1.4
  intro_slider: ^1.1.5
  logging: ^0.11.3+2
  scoped_model: ^1.0.1
  shared_preferences: ^0.4.3
  shimmer: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

